In [2]:
#Create a numpy array starting from 2 till 50 with a stepsize of 3.
import numpy as np
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [10]:
#Accept two lists of 5 elements each from the user.
#Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.
import numpy
a = []
b = []
for i in range(5):
    s = int(input(""))
    a.append(s)
print(a)

for x in range(5):
    r = int(input(""))
    b.append(r)
print(b)
arr1 = numpy.array(a)    #converting 'a' list into numpy array
arr2 = numpy.array(b)    #converting 'b' list into numpy array
print(arr1)               
print(arr2)             #printing array

c = numpy.concatenate((arr1,arr2))  #concate two array
print(c)

numpy.sort(c)       #perform sorting on concated array


12
5
8
4
6
[12, 5, 8, 4, 6]
0
25
14
12
46
[0, 25, 14, 12, 46]
[12  5  8  4  6]
[ 0 25 14 12 46]
[12  5  8  4  6  0 25 14 12 46]


array([ 0,  4,  5,  6,  8, 12, 12, 14, 25, 46])

In [9]:
#Write a code snippet to find the dimensions of a ndarray and its size.
import numpy as np
arr = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
print(arr)
print("Dimension of array:",arr.ndim)
print("Size of array:",arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of array: 2
Size of array: 9


In [11]:
#How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
import numpy as np
arr = np.array([1,2,3,4,10,20,30,40])
array_2d = np.reshape(arr,(4,2))
print(array_2d)
print(array_2d.ndim)  # printing dimension of array.

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
2
